### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Kurren123** [SofusA/roslyn-language-server#2]
If it's okay with you, I might add a few bullet points to the readme of this project just to describe what it's doing. Correct me if I am wrong, but it seems like this wrapper:

1. Starts the language server and relays stuff between the named pipe and stdio
2. Responds to the `initialize` server notification with a `solution/open` notification

I might investigate the possibility of either forking Rozlyn and adding this functionality myself, or making my own version of this project but written in .net instead of Rust. This is because in .net I can reference the `Microsoft.CodeAnalysis.LanguageServer` dll rather than have to spawn a new language server process, possibly avoiding named pipes entirely.

**Comment by SofusA** [comment]
Sure that would be great! 
Any contribution would be awesome!

i was also considering these two possibilities. 

I think the best solution would be to add a `—stdin` flag to `Microsoft.CodeAnalysis.LanguageServer`, and a way to make it find solutions and projects automatically. But I don’t think it is in the scope as they only focus is vscode. 

Please let me know if have any success

**Comment by SofusA** [comment]
I implemented support for `csproj` files today. 
And since nixpkgs updated `Microsoft.CodeAnalysis.LanguageServer` from 4.10 to 4.12 i also found that they no longer support dynamic registration to be false for diagnostics for the client. 

This is very unfortunate.

I "solved" this by patching the server capability response tricking the client to believe that the server has this capability. 
This adds to the list of cursed behaviour of `Microsoft.CodeAnalysis.LanguageServer`
